#!/usr/bin/env bash
# displays subdomain info

function subinfo {
	 if [ -z $2 ] ; then
	    wwwsub="www.$1"
	    www_rec_type="$(dig $wwwsub | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')"
	    www_ip="$(dig $wwwsub | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')"
	    echo "The subdomain www is a $www_rec_type record and points to $www_ip"
	    lb1sub="lb-01.$1"
	    lb_rec_type="$(dig $lb1sub | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')"
	    lb_ip="$(dig $lb1sub | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')"
	    echo "The subdomain lb-01 is a $lb_rec_type record and points to $lb_ip"
	    web1sub="web-01.$1"
	    web1_rec_type="$(dig $web1sub | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')"
	    web1_ip="$(dig $web1sub | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')"
	    echo "The subdomain web-01 is a $web1_rec_type record and points to $web1_ip"
	    web2sub="web-02.$1"
	    web2_rec_type="$(dig $web2sub | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')"
	    web2_ip="$(dig $web2sub | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')"
	    echo "The subdomain web-02 is a $web2_rec_type record and points to $web2_ip"

	 elif [ $# -eq 2 ] ; then
	    subdomain="$2.$1"
	    rec_type="$(dig $subdomain | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')"
	    ip="$(dig $subdomain | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')"
	    echo "The subdomain $2 is a $rec_type record and points to $ip"
	 fi
}

subinfo $1 $2