#!/usr/bin/env bash
# Configures a new load balancer
apt-get -y update
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
printf "\n\nfrontend fe_main\n\tmode http\n\tbind *:80\n\tdefault_backend be_main\n\nbackend be_main\n\tmode http\n\tbalance roundrobin\n\tserver 718-web-01 35.231.100.106\n\tserver 718-web-02 35.237.151.115" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
