#!/usr/bin/env bash
# Backups all SQL databases and compresses them
THEDATE=$(date +'%d-%m-%Y')
mysqldump --user=root --password="$1" -ulocahost --all-databases > backup.sql
tar -cvzf '$THEDATE'tar.gz backup.sql
