#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd,
# using the while loop + IFS.

while IFS=: read -r f1 f4 f6 f7 f3 f2 f5; do
    echo "The user $f1 is part of the $f2 gang, lives in $f3 and rides $f4. $f5's place is protected by the passcode $f6, more info about the user here: $f7"

done</etc/passwd
