#!/usr/bin/env bash
# Changes root user to nginx for web server
pkill apache2
sed -i 's/80 default_server default_server/' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod -R 777 /etc/nginx
sudo -u nginx systemctl start nginx
